# Generated by Django 5.1.3 on 2026-06-06 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_controlsetpoint_setpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationnode',
            name='room_id',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='api.room', to_field='room_id', verbose_name='Refering to id of room where this node is implemented'),
        ),
    ]
