# Generated by Django 5.1.3 on 2026-06-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_rawsensormonitor_room_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(db_column='role', default=2),
        ),
    ]
